// <auto-generated />
using System;
using DataAccessLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(YuutaDbContext))]
    [Migration("20201029214341_Events")]
    partial class Events
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.6.20312.4");

            modelBuilder.Entity("DataAccessLayer.Models.ChannelModels.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelDid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.HasIndex("GuildId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.CommandRestrictionOverload", b =>
                {
                    b.Property<int>("RestrictionOverloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Authorize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildDid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleDid")
                        .HasColumnType("INTEGER");

                    b.HasKey("RestrictionOverloadId");

                    b.HasIndex("CommandId");

                    b.ToTable("CommandRestrictionOverloads");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.YuutaCommand", b =>
                {
                    b.Property<int>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommandType")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommandId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Events.DirectMessageEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserToSend")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("GuildId");

                    b.ToTable("DirectMessageEvents");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Events.GuildMessageEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelToSend")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMessageEvents");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Events.RoleEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleEventType")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("User")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("GuildId");

                    b.ToTable("RoleEvents");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildMacroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentId");

                    b.HasIndex("GuildMacroId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Guild", b =>
                {
                    b.Property<int>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildDid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.GuildMacro", b =>
                {
                    b.Property<int>("GuildMacroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteAfterSend")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildMacroId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMacros");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessage", b =>
                {
                    b.Property<int>("RoleMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelDid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageDid")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleMessageId");

                    b.HasIndex("GuildId");

                    b.ToTable("RoleMessages");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessageItem", b =>
                {
                    b.Property<int>("RoleMessageItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmojiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleMessageItemId");

                    b.HasIndex("RoleMessageId");

                    b.ToTable("RoleMessageItems");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RoleModels.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleDid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoleMessageItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId");

                    b.HasIndex("RoleMessageItemId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChannelModels.Channel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.CommandRestrictionOverload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.CommandModels.YuutaCommand", "Command")
                        .WithMany("RestrictionOverloads")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Events.DirectMessageEvent", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Events.GuildMessageEvent", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Events.RoleEvent", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Attachment", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.GuildMacro", "GuildMacro")
                        .WithMany("Attachments")
                        .HasForeignKey("GuildMacroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Guild", b =>
                {
                    b.OwnsOne("DataAccessLayer.Models.GuildModels.GuildSettings", "GuildSettings", b1 =>
                        {
                            b1.Property<int>("GuildSettingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GoodbyeChannel")
                                .HasColumnType("TEXT");

                            b1.Property<string>("GoodbyeMessage")
                                .HasColumnType("TEXT");

                            b1.Property<int>("GuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("WelcomeChannel")
                                .HasColumnType("TEXT");

                            b1.Property<string>("WelcomeMessage")
                                .HasColumnType("TEXT");

                            b1.HasKey("GuildSettingId");

                            b1.HasIndex("GuildId")
                                .IsUnique();

                            b1.ToTable("GuildSettings");

                            b1.WithOwner()
                                .HasForeignKey("GuildId");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.GuildMacro", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany("GuildMacros")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessage", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany("RoleMessages")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessageItem", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessage", "RoleMessage")
                        .WithMany("RoleMessageItems")
                        .HasForeignKey("RoleMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.RoleModels.Role", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessageItem", null)
                        .WithMany("RolesToAdd")
                        .HasForeignKey("RoleMessageItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
