// <auto-generated />
using System;
using DataAccessLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(YuutaDbContext))]
    [Migration("20200623223008_GuildSettings")]
    partial class GuildSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("DataAccessLayer.Models.ChannelModels.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChannelDid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.HasIndex("ChannelTypeId");

                    b.HasIndex("GuildId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChannelModels.ChannelType", b =>
                {
                    b.Property<int>("ChannelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelTypeId");

                    b.ToTable("ChannelTypes");

                    b.HasData(
                        new
                        {
                            ChannelTypeId = 0,
                            Description = "Normal",
                            Name = "Normal"
                        },
                        new
                        {
                            ChannelTypeId = 1,
                            Description = "BotChannel",
                            Name = "BotChannel"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.CommandRestrictionOverload", b =>
                {
                    b.Property<int>("RestrictionOverloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Authorize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildDid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleDid")
                        .HasColumnType("INTEGER");

                    b.HasKey("RestrictionOverloadId");

                    b.HasIndex("CommandId");

                    b.ToTable("CommandRestrictionOverloads");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.CommandType", b =>
                {
                    b.Property<int>("CommandTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CommandTypeId");

                    b.ToTable("CommandTypes");

                    b.HasData(
                        new
                        {
                            CommandTypeId = 0,
                            Description = "Normal",
                            Name = "Normal"
                        },
                        new
                        {
                            CommandTypeId = 1,
                            Description = "ForcedGlobal",
                            Name = "ForcedGlobal"
                        },
                        new
                        {
                            CommandTypeId = 2,
                            Description = "StaffOnly",
                            Name = "StaffOnly"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.YuutaCommand", b =>
                {
                    b.Property<int>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandTrigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommandTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommandId");

                    b.HasIndex("CommandTypeId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildMacroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentId");

                    b.HasIndex("GuildMacroId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Guild", b =>
                {
                    b.Property<int>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildDid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuildSettingsGuildSettingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildSettingsGuildSettingId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.GuildMacro", b =>
                {
                    b.Property<int>("GuildMacroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteAfterSend")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildMacroId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMacros");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.GuildSettings", b =>
                {
                    b.Property<int>("GuildSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoodbyeChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodbyeMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("WelcomeChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildSettingId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessage", b =>
                {
                    b.Property<int>("RoleMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChannelDid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageDid")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleMessageId");

                    b.HasIndex("GuildId");

                    b.ToTable("RoleMessages");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessageItem", b =>
                {
                    b.Property<int>("RoleMessageItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmojiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleMessageItemId");

                    b.HasIndex("RoleMessageId");

                    b.ToTable("RoleMessageItems");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RoleModels.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleDid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoleMessageItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId");

                    b.HasIndex("RoleMessageItemId");

                    b.HasIndex("RoleTypeId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RoleModels.RoleType", b =>
                {
                    b.Property<int>("RoleTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleTypeId");

                    b.ToTable("RoleTypes");

                    b.HasData(
                        new
                        {
                            RoleTypeId = 0,
                            Description = "Normal",
                            Name = "Normal"
                        },
                        new
                        {
                            RoleTypeId = 1,
                            Description = "GlobalCommands",
                            Name = "GlobalCommands"
                        },
                        new
                        {
                            RoleTypeId = 2,
                            Description = "GlobalMacros",
                            Name = "GlobalMacros"
                        },
                        new
                        {
                            RoleTypeId = 3,
                            Description = "Staff",
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChannelModels.Channel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChannelModels.ChannelType", "ChannelType")
                        .WithMany()
                        .HasForeignKey("ChannelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.CommandRestrictionOverload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.CommandModels.YuutaCommand", "Command")
                        .WithMany("RestrictionOverloads")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommandModels.YuutaCommand", b =>
                {
                    b.HasOne("DataAccessLayer.Models.CommandModels.CommandType", "CommandType")
                        .WithMany()
                        .HasForeignKey("CommandTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Attachment", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.GuildMacro", "GuildMacro")
                        .WithMany("Attachments")
                        .HasForeignKey("GuildMacroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.Guild", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.GuildSettings", "GuildSettings")
                        .WithMany()
                        .HasForeignKey("GuildSettingsGuildSettingId");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.GuildMacro", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany("GuildMacros")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessage", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessageItem", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessage", "RoleMessage")
                        .WithMany("RoleMessageItems")
                        .HasForeignKey("RoleMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.RoleModels.Role", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GuildModels.Guild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.GuildModels.RoleMessages.RoleMessageItem", null)
                        .WithMany("RolesToAdd")
                        .HasForeignKey("RoleMessageItemId");

                    b.HasOne("DataAccessLayer.Models.RoleModels.RoleType", "RoleType")
                        .WithMany()
                        .HasForeignKey("RoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
